### ISSUE TITLE
Implement the setting page to the back end

### ISSUE THREAD

**Issue by peterkapena** [peterkapena/globetalk-front#1]

**Comment by andreKiona** [comment]
Linked the term of use page, add payment method page, about us page and Privacy Policy page to the Settings pages

Help is required to setup the button to save the change on the password.

**Comment by peterkapena** [comment]
Hi @andreKiona ,

I have fixed the back end findOneAndUpdate function for updating the password from the setting page. we can work on setting this on the front end tomorrow during the day as I am not available tomorrow night and tonight. If you are available tomorrow then plz schedule a session during the day. You can pull latest in case you want to see what i did

**Comment by andreKiona** [comment]
Noted ✅️

**Comment by andreKiona** [comment]
Settings Page Changes UI updated. Kindly check and provide feedback. thank you
